name: CI ISO Build

on:
  push:
    branches:
      - main

env:
  ISO_NAME: ${{ vars.ISO_NAME || "omarchy" }}
  RELEASE_DATE: ${{ format('{0:yyyyMMdd}', github.event.issue.created_at) }}

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: recursive
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build ISO
      run: ./bin/omarchy-iso-make --no-boot-offer
        
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ISO_NAME }}-iso-${{ env.RELEASE_DATE }}
        path: release/*.iso