name: CI ISO Build

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    # container:
    #   image: archlinux/archlinux:latest
    #   options: --privileged
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build ISO in Arch Linux container
      run: |
        docker run --rm \
          --privileged \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          archlinux:latest \
          bash -c "
            pacman -Syu --noconfirm && \
            chmod +x build_iso.sh && \
            ./build_iso.sh
          "
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: omarchy-iso-${{ github.run_number }}
        path: out/*.iso