name: CI ISO Build

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: recursive
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build ISO
      run: ./bin/omarchy-iso-make --no-boot-offer
        
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: omarchy-iso-${{ github.run_number }}
        path: release/*.iso